services:
  - type: web
    name: megabot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: KEEP_ALIVE_URL
        sync: false
      - key: PORT
        value: 8080
